### ISSUE TITLE
e2e tests using outdated client

### ISSUE THREAD

**Issue by mboersma** [deis/e2e-runner#63]
At least in some cases, such as https://ci.deis.io/job/workflow-test-pr/9021/console. Needs investigating.

**Comment by vdice** [comment]
I'm not sure what the issue was, but it appears to have been temporary.  I've combed through the last dozen runs of the [workflow-test](https://ci.deis.io/job/workflow-test) job and have only seen it use the (correct) latest: `Workflow CLI Version 'v2.8.0-8782839' installed.`  

Please reopen if this behavior is once again detected...
