### ISSUE TITLE
If build is aborted we should clean up cluster lease

### ISSUE THREAD

**Issue by jchauncey** [deis/e2e-runner#8]

**Comment by vdice** [comment]
@jchauncey what are your thoughts on priority for fixing this?

**Comment by jchauncey** [comment]
hrm not sure. Im not sure of a good way to do it

**Comment by vdice** [comment]
@jchauncey we could set up a [Post-Build Task](https://wiki.jenkins-ci.org/display/JENKINS/Post+build+task) in the appropriate Jenkins job, like mentioned [here](http://stackoverflow.com/a/25543380/6520554) -- the trick is having the necessary info for making the k8s-claimer command in the shell at that point (namely the auth token and lease token).  

Otherwise, it looks like the leased cluster duration of 1600 seconds is relatively short enough, combined with our making a larger number of leasable clusters available, that the impacts of this bug aren't so severe.

**Comment by bacongobbler** [comment]
Indeed, I don't think this is much of an issue because of how we handle the cluster via k8s-claimer. Closing this unless we feel it's still valuable to implement this.
